name: Angerona
image: ubuntu-14-04-x64
min_size: 1gb
config:
  #first_run
  packages:
    - git
    - docker.io
  runcmd:
    - cd /home/docker && git clone git://github.com/selfcommit/angerona.git && cd angerona && bash setup.sh